MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data1/pbdata/data_zk/Faster-ILOD/incremental_learning_ResNet50_C4/15_5_new_split/first_step/model_trim_optimizer_iteration.pth"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 0
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 21 # total classes : 20 + 1
    SPLIT: '15+5'
    INCREMENTAL: True
  PROTO_ON: True # enable box + proto head
  STORAGE_ENABLE: True # memory bank
  HIDDEN_DIM: 256
  QLEN: 32768
  TEMPERATURE: 0.2
  CONTRAST_IOU_THRES: 0.5
  REWEIGHT_TYPE: 'none'
  LAMB_CONTRAST: 0.5
  PSEUDO_WEIGHT: 1.

DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  BASE_LR: 0.0001 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (30000,)
  MAX_ITER: 40000 # number of iteration
  CHECKPOINT_PERIOD: 2500 # number of iteration to generate check point
  IMS_PER_BATCH: 1 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
# OUTPUT_DIR: "/home/zhengkai/Faster-ILOD/incremental_learning_ResNet50_C4/15_5" # path to store the result
# TENSORBOARD_DIR: "/home/zhengkai/Faster-ILOD/incremental_learning_ResNet50_C4/15_5/tensorboard"